{
 "title": "CU-CP",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"id\" FROM \"cu_cp\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "AMFs connected",
   "type": "stat",
   "description": "Number of AMFs connected",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"amf_name\", \"connected\" FROM \"ngaps\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
    }
   ]
  },
  {
   "title": "AMFs configured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 1 }
   ]
  },
  {
   "title": "DUs connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT \"gnb_du_id\" FROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo GROUP BY \"gnb_du_id\" "
    }
   ]
  },
  {
   "title": "AMFs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "AMF connection status",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 1 }
     ]
    }
   ]
  },
  {
   "title": "DUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected DU IDs",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "iox",
       "rawSql": "SELECT \"gnb_du_id\" FROM \"rrcs\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo "
      }
     ]
    }
   ]
  }
 ]
}